FROM hseeberger/scala-sbt:8u181_2.12.8_1.2.8 AS builder

# set up directories
WORKDIR /workdir
COPY ./project/plugins.sbt /workdir/project/plugins.sbt
COPY ./project/workdir.properties /workdir/project/workdir.properties
COPY ./.scalafmt.conf /workdir/.scalafmt.conf

# fetch documents into image
COPY ./workdir.sbt /workdir/workdir.sbt
RUN sbt assembly

COPY ./src /workdir/src
RUN sbt assembly
